import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Link from "next/link";
import Header from "@/components/Header";

const integralCF = localFont({
  src: "../public/fonts/integralcf-bold.otf",
  variable: '--font-integralcf',
})

const satoshi = localFont({
  src: [
    {
      path: '../public/fonts/Satoshi-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Satoshi-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../public/fonts/Satoshi-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-satoshi',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isAuthenticated = false;

  return (
    <html lang="en">
      <body
        className={`${integralCF.variable} ${satoshi.variable} antialiased`}
      >
        {!isAuthenticated && (
          <div className="bg-black w-full py-3 text-center">
            <p className="text-white body-regular">Sign up and get 20% off to your first order. <Link href="/sign-up" className="underline body-medium hover:opacity-70">Sign Up Now</Link></p>
          </div>
        )}
        <Header />
        {children}
      </body>
    </html>
  );
}
